--Chinese (by duowan)

IWOWQUERY_QH_TITLE = "duowan.com任务库查询";
IWOWQUERY_QH_QUERYRESULT1 = "查询结果:";
IWOWQUERY_QH_QUERYRESULT2 = "个任务";
IWOWQUERY_QUESTOBJECT_FILTER1 = "已杀死";
IWOWQUERY_QUESTOBJECT_FILTER2 = "：.*";

IWOWQUERY_TEXT_TOOLTIP1 = "]任务目标[";
IWOWQUERY_TEXT_TOOLTIP2 = "]获得: ";
IWOWQUERY_TEXT_TOOLTIP3 = " 位于 ";
IWOWQUERY_TEXT_TOOLTIP4 = "任务: ";
IWOWQUERY_TEXT_TOOLTIP5 = "|cff00ffff区域 ";
IWOWQUERY_TEXT_TOOLTIP6 = " 中的地图标记过多，请删除部分。|r";
IWOWQUERY_TEXT_TOOLTIP7 = "|cFFFFFF00任务查询(任务物品获得)|r\n|cFF00FF00";
IWOWQUERY_TEXT_TOOLTIP8 = "|cFFFFFF00任务查询(接受任务地点)|r\n";
IWOWQUERY_TEXT_TOOLTIP9 = "|cFFFFFF00任务查询(完成任务地点)|r\n";

IWOWQUERY_TEXT_ACCEPTQUEST = "接受任务";
IWOWQUERY_TEXT_COMPLETEQUEST = "完成任务";
IWOWQUERY_TEXT_ACCEPTQUESTLOCATION = "接受任务地点";
IWOWQUERY_TEXT_COMPLETEQUESTLOCATION = "完成任务地点";

IWOWQUERY_TEXT_DELETEBUTTON = "删除查询标记";
IWOWQUERY_TEXT_BACKBUTTON = "返回任务说明";
IWOWQUERY_TEXT_QUERYBUTTON = "地点查询";
IWOWQUERY_TEXT_SEARCHBUTTON = "任务搜索";
IWOWQUERY_TEXT_SEARCHBUTTON_TOOLTIP = "根据你输入的条件查找任务。\n例如输入\"哀嚎洞穴\"，就可以\n查找到所有哀嚎洞穴相关的任务。";
