CT_RABOSS_TRASH_BOSSNAME			= "纳克萨玛斯小怪";
CT_RABOSS_TRASH_INFO				= "当纳克萨玛斯小怪施放各种技能时向团队发出警报。";
CT_RABOSS_TRASH_PC_ALERT			= "破胆怒吼报警";
CT_RABOSS_TRASH_PC_ALERT_INFO			= "破胆怒吼报警";
CT_RABOSS_TRASH_INFECTIOUSN			= "吃人的食尸鬼"
CT_RABOSS_TRASH_INFECTIOUS			= "变得愤怒了！";
CT_RABOSS_TRASH_INFECTRAGE			= "*** 食尸鬼变得愤怒 ***";
CT_RABOSS_TRASH_PLAGUEDN			= "疫病食尸鬼"
CT_RABOSS_TRASH_PLAGUED				= "变得愤怒了！";
CT_RABOSS_TRASH_PLAGUEDRAGE			= "*** 食尸鬼变得愤怒 ***"
CT_RABOSS_TRASH_GARGOYLE			= "发出奇怪的声音。";
CT_RABOSS_TRASH_GARGOYLEBURN			= "*** 全力攻击 ***";
CT_RABOSS_TRASH_DKCAPT				= "死亡骑士队长[ ]*获得了[ ]*旋风斩[ ]*的效果。";
CT_RABOSS_TRASH_DKCAPTWARN			= "*** 旋风斩！--近战后退 ***";
CT_RABOSS_TRASH_NECROSTALKER			= "受到了破胆怒吼";
CT_RABOSS_TRASH_NECROSTALKERWARN		= "*** 破胆怒吼 ***";

-- Anub'Rekhan
CT_RABOSS_ANUBREKHAN_INFO				= "当阿努布雷坎发动虫群风暴和结束时向团队发出警报。";
CT_RABOSS_ANUBREKHAN_DEATH				= "玩家死亡时发出警报";
CT_RABOSS_ANUBREKHAN_DEATH_INFO			= "启用后，提示玩家死亡。";
CT_RABOSS_ANUBREKHAN_SWARMEND_TIMER			= "虫群风暴结束计时";
CT_RABOSS_ANUBREKHAN_SWARM_TIMER			= "虫群风暴";
CT_RABOSS_ANUBREKHAN_YELL1_DETECT			= "你们逃不掉的。";
CT_RABOSS_ANUBREKHAN_YELL2_DETECT			= "一些小点心……";
CT_RABOSS_ANUBREKHAN_YELL3_DETECT			= "对，跑吧！那样伤口出血就更多了！";
CT_RABOSS_ANUBREKHAN_YELL_END_DETECT		= "嘘……很快一切就都结束了。";
CT_RABOSS_ANUBREKHAN_DEATH_DETECT			= "阿努布雷坎[ ]*死亡了。";
CT_RABOSS_ANUBREKHAN_SWARM_GAIN_DETECT		= "阿努布雷坎[ ]*获得了[ ]*虫群风暴[ ]*的效果。";
CT_RABOSS_ANUBREKHAN_SWARM_CAST_DETECT		= "阿努布雷坎[ ]*开始施放[ ]*虫群风暴[ ]*。";
CT_RABOSS_ANUBREKHAN_SWARM_FADE_DETECT		= "虫群风暴[ ]*效果从[ ]*阿努布雷坎[ ]*身上消失。";
CT_RABOSS_ANUBREKHAN_DEATHPLAYER_DETECT		= "^([^%s]+)[ ]*死亡了。$";
CT_RABOSS_ANUBREKHAN_DEATHSELF_DETECT		= "^([^%s]+)[ ]*死了。$";
CT_RABOSS_ANUBREKHAN_SWARM_PREALERT			= "*** %s-%s 秒后虫群风暴 ***";
CT_RABOSS_ANUBREKHAN_SWARM_IMMINENT_ALERT	= "*** 虫群风暴 - 3 秒后发动 ***";
CT_RABOSS_ANUBREKHAN_SWARM_ALERT			= "*** 虫群风暴开始 - 持续20秒 ***";
CT_RABOSS_ANUBREKHAN_SWARM_END_PREALERT		= "*** 虫群风暴 %s 秒后结束 ***";
CT_RABOSS_ANUBREKHAN_SWARM_END_ALERT		= "*** 虫群风暴结束 ***";
CT_RABOSS_ANUBREKHAN_SCARAB_SPAWN_ALERT		= "*** %s死亡 - 死尸甲虫出现 ***";

-- Grand Widow Faerlina
CT_RABOSS_FAERLINA_INFO						= "当黑女巫法琳娜狂怒和压制时发出警报。";

CT_RABOSS_FAERLINA_YELL1					= "休想从我面前逃掉！";
CT_RABOSS_FAERLINA_YELL2					= "以主人之名，杀了他们！";
CT_RABOSS_FAERLINA_YELL3					= "逃啊！有本事就逃啊！";
CT_RABOSS_FAERLINA_YELL4					= "跪下求饶吧，懦夫！";
CT_RABOSS_FAERLINA_END						= "主人……会为我复仇雪耻的！";
CT_RABOSS_FAERLINA_WIDOWEMBRACE_DETECT		= "黑女巫法琳娜[ ]*受到了[ ]*黑女巫的拥抱[ ]*效果的影响。";

CT_RABOSS_FAERLINA_ENGAGE					= "*** 60-75 秒后第一次激怒 ***";
CT_RABOSS_FAERLINA_ENRAGE_PREALERT			= "*** %s 秒后激怒 ***";
CT_RABOSS_FAERLINA_ENRAGE_ALERT				= "*** 激怒 ***";
CT_RABOSS_FAERLINA_ENRAGE_TIMER				= "激怒";
CT_RABOSS_FAERLINA_ENRAGEREADY				= "*** 即将激怒 ***";
CT_RABOSS_FAERLINA_ENRAGE_SILENCE_ALERT		= "*** %s 秒后激怒 ***";
CT_RABOSS_FAERLINA_SILENCE_ALERT			= "*** 压制激怒 - 30秒时间 ***";
CT_RABOSS_FAERLINA_SILENCE_TIMER			= "压制时间";

-- MAEXXNA
CT_RABOSS_MAEXXNA_INFO						= "当迈克斯纳发动蛛网裹体和蛛网喷射时向团队发出警报";
CT_RABOSS_MAEXXNA_WRAP_ALERT				= "蛛网裹体";
CT_RABOSS_MAEXXNA_WRAP_ALERT_INFO			= "发出蛛网裹体警报。";
CT_RABOSS_MAEXXNA_ENGAGE					= "*** 迈克斯纳战斗开始 ***";
CT_RABOSS_MAEXXNA_SPRAYSTRING				= "蛛网喷射";
CT_RABOSS_MAEXXNA_WEBSPRAY_TIMER			= "蛛网喷射";
CT_RABOSS_MAEXXNA_SPIDERS_TIMER				= "小蜘蛛";
CT_RABOSS_MAEXXNA_SPIDERS5SEC				= "*** 小蜘蛛 5 秒后出现 ***";
CT_RABOSS_MAEXXNA_5SEC						= "*** 5 秒后蛛网喷射 ***";
CT_RABOSS_MAEXXNA_SPRAYWARN					= "*** 蛛网喷射 - 40秒后再次发动 ***";
CT_RABOSS_MAEXXNA_WWEXP						= "^([^%s]+)[ ]*受到了[ ]*蛛网裹体";
CT_RABOSS_MAEXXNA_WRAPPED_YOU				= "*** 你中了蛛网裹体 ***";
CT_RABOSS_MAEXXNA_WRAPPED					= "*** %s 中了蛛网裹体 ***";
CT_RABOSS_MAEXXNA_WRAPPED_TIMER				= "蛛网裹体";
CT_RABOSS_MAEXXNA_ENRAGESTRING				= "%s变得愤怒了！";
CT_RABOSS_MAEXXNA_ENRAGEWARN				= "*** 激怒 ***";

-- Patchwerk
CT_RABOSS_PATCHWERK_BOSSNAME				= "帕奇维克";
CT_RABOSS_PATCHWERK_INFO					= "当帕奇维克极度狂暴时向团队发出警报。";
CT_RABOSS_PATCHWERK_YELL1					= "帕奇维克要跟你玩！";
CT_RABOSS_PATCHWERK_YELL2					= "帕奇维克是克尔苏加德的战神！";
CT_RABOSS_PATCHWERK_DEAD					= "怎么……搞的……";
CT_RABOSS_PATCHWERK_ENGAGED					= "*** 帕奇维克战斗开始 - 7分钟后狂暴 ***";
CT_RABOSS_PATCHWERK_1MINWARN				= "*** 1 分钟后狂暴 ***";
CT_RABOSS_PATCHWERK_MINWARN					= "*** %s 分钟后狂暴 ***";
CT_RABOSS_PATCHWERK_SECWARN					= "*** %s 秒后狂暴 ***";
CT_RABOSS_PATCHWERK_BERSERK_TIMER			= "狂暴";
CT_RABOSS_PATCHWERK_ENRAGESTRING			= "%s变得愤怒了！";
CT_RABOSS_PATCHWERK_BERSERKSTRING			= "%s变得狂暴了！";
CT_RABOSS_PATCHWERK_ENRAGEWARNING			= "*** 激怒 ***";
CT_RABOSS_PATCHWERK_BERSERKWARNING			= "*** 极度狂暴 ***";

-- Grobbulus
CT_RABOSS_GROBBULUS_INFO					= "当你或附近玩家受到了变异注射效果影响时向团队发出警报。";
CT_RABOSS_GROBBULUS_ALERT					= "警告附近玩家";
CT_RABOSS_GROBBULUS_ALERT_INFO				= "警告附近玩家受到了变异注射。";
CT_RABOSS_GROBBULUS_TELL					= "通知目标";
CT_RABOSS_GROBBULUS_TELL_INFO				= "发送一条密语给中了变异注射的玩家。";
CT_RABOSS_GROBBULUS_BSLIME					= "轰击软泥";
CT_RABOSS_GROBBULUS_BSLIME_INFO				= "显示轰击软泥计时器。";
CT_RABOSS_GROBBULUS_ENGAGED					= "*** 格罗布鲁斯战斗开始 ***";
CT_RABOSS_GROBBULUS_SSPRAY_DETECT			= "^格罗布鲁斯[ ]*的[ ]*软泥喷射";
CT_RABOSS_GROBBULUS_SSPRAY_TIMER			= "软泥喷射";
CT_RABOSS_GROBBULUS_SSPRAY_WARN				= "*** 软泥喷射 - 30 秒后再次发动 ***";
CT_RABOSS_GROBBULUS_SSPRAY_5SEC				= "*** 5 秒后软泥喷射 ***";
CT_RABOSS_GROBBULUS_MIEXP					= "^([^%s]+)[ ]*受到了[ ]*变异注射";
CT_RABOSS_GROBBULUS_POISON_CLOUD_DETECT		= "格罗布鲁斯[ ]*施放了[ ]*毒性云雾[ ]*。";
CT_RABOSS_GROBBULUS_POISON_CLOUD_TIMER		= "毒性云雾";
CT_RABOSS_GROBBULUS_BSLIME_DETECT			= "格罗布鲁斯[ ]*开始施放[ ]*轰击软泥[ ]*。";
CT_RABOSS_GROBBULUS_BSLIME_TIMER			= "轰击软泥";
CT_RABOSS_GROBBULUS_AFFLICTED_YOU		= "*** 你中了变异注射 ***";
CT_RABOSS_GROBBULUS_AFFLICTED			= "*** %s 中了变异注射 ***";

-- Gluth
CT_RABOSS_GLUTH_INFO						= "当格拉斯施放群体恐惧和狂暴时向团队发出警报。";
CT_RABOSS_GLUTH_FRENZY_ALERT				= "狂暴警报";
CT_RABOSS_GLUTH_FRENZY_ALERT_INFO			= "狂暴时发出警报。";
CT_RABOSS_GLUTH_FEAR_ALERT					= "群体恐惧";
CT_RABOSS_GLUTH_FEAR_ALERT_INFO				= "群体恐惧预警。";
CT_RABOSS_GLUTH_ENGAGED						= "*** 格拉斯战斗开始 ***";
CT_RABOSS_GLUTH_DEVOURSTRING				= "%s准备吞噬一个僵尸！";
CT_RABOSS_GLUTH_FRENZYSTRING				= "%s变得狂怒无比！";
CT_RABOSS_GLUTH_FRENZYWARNING				= "*** 狂暴 - 猎人立刻使用宁神射击！ ***";
CT_RABOSS_GLUTH_DECIMATE_TIMER				= "残杀";
CT_RABOSS_GLUTH_DECIMATESOON				= "*** 残杀即将来临 ***";
CT_RABOSS_GLUTH_DECIMATESTRING				= "残杀"
CT_RABOSS_GLUTH_DECIMATEWARNING				= "***  残杀 - AOE 僵尸！ ***";
CT_RABOSS_GLUTH_FEARSTRING					= "恐惧怒吼";
CT_RABOSS_GLUTH_FEARWARNING					= "*** 群体恐惧 - 20秒后再次发动 ***";
CT_RABOSS_GLUTH_FEAR5SEC					= "*** 5 秒后群体恐惧  ***";
CT_RABOSS_GLUTH_FEAR_TIMER					= "群体恐惧";

-- Thaddius
CT_RABOSS_THADDIUS_INFO						= "显示极性转换、激怒和能量涌动警报。";
CT_RABOSS_THADDIUS_SURGE_ALERT				= "能量涌动";
CT_RABOSS_THADDIUS_SURGE_ALERT_INFO			= "当斯塔拉格获得能量涌动时向团队发出警报。";
CT_RABOSS_THADDIUS_MOVE_ALERT				= "跑位提示";
CT_RABOSS_THADDIUS_MOVE_ALERT_INFO			= "极性变换后的跑位提示。";
CT_RABOSS_THADDIUS_PVPDAMAGE_REPORT                = "跑位错误电击队友报告";
CT_RABOSS_THADDIUS_PVPDAMAGE_REPORT_INFO        = "统计和报告跑位错误电击队友的人员";
CT_RABOSS_THADDIUS_PHASE1_YELL1				= "斯塔拉格要碾碎你！";
CT_RABOSS_THADDIUS_PHASE1_YELL2				= "主人要吃了你！";
CT_RABOSS_THADDIUS_PHASE2_YELL1				= "咬碎……你的……骨头……";
CT_RABOSS_THADDIUS_PHASE2_YELL2				= "杀……";
CT_RABOSS_THADDIUS_PHASE2_YELL3				= "打……烂……你！";
CT_RABOSS_THADDIUS_DEAD						= "感谢……你……";
CT_RABOSS_THADDIUS_PHASE1					= "*** 第一阶段 ***";
CT_RABOSS_THADDIUS_PHASE2					= "*** 第二阶段 ***";
CT_RABOSS_THADDIUS_SURGE					= "*** 能量涌动 ***";
CT_RABOSS_THADDIUS_SURGESTRING				= "斯塔拉格[ ]*获得了[ ]*能量涌动[ ]*的效果。";
CT_RABOSS_THADDIUS_SHIFTSTRING				= "塔迪乌斯[ ]*施放了[ ]*极性转化[ ]*。";
CT_RABOSS_THADDIUS_SHIFTWARN				= "*** 极性转化 - 检查Debuff ***";
CT_RABOSS_THADDIUS_POLARITY					= "极性转化";
CT_RABOSS_THADDIUS_POLARITYSTRING			= "塔迪乌斯[ ]*开始施放[ ]*极性转化[ ]*。";
CT_RABOSS_THADDIUS_POLARITY_TIMER			= "极性转化";
CT_RABOSS_THADDIUS_POLARITYWARN				= "*** 正在施放极性转换 ***";
CT_RABOSS_THADDIUS_POSITIVEWARN				= "+++ 正电极 +++";
CT_RABOSS_THADDIUS_NEGATIVEWARN				= "--- 负电极 ---";
CT_RABOSS_THADDIUS_LEFTWARN					= "<<< 向左移动 <<<";
CT_RABOSS_THADDIUS_RIGHTWARN				= ">>> 向右移动 >>>";
CT_RABOSS_THADDIUS_POSITIVE					= "Interface\\Icons\\Spell_ChargePositive";
CT_RABOSS_THADDIUS_NEGATIVE					= "Interface\\Icons\\Spell_ChargeNegative";
CT_RABOSS_THADDIUS_1MINWARN					= "*** 1 分钟后狂暴 ***";
CT_RABOSS_THADDIUS_WARN						= "*** %s 分钟后狂暴 ***";
CT_RABOSS_THADDIUS_SECWARN					= "*** %s 秒后狂暴 ***";
CT_RABOSS_THADDIUS_BERSERKSTRING_TIMER		= "狂暴";
CT_RABOSS_THADDIUS_BERSERKSTRING			= "%s变得极度狂暴而愤怒！";
CT_RABOSS_THADDIUS_BERSERKWARNING			= "*** 狂暴 ***";
CT_RABOSS_THADDIUS_THROWMSG					= "*** 投掷 ***";
CT_RABOSS_THADDIUS_THROWMSG5				= "*** 5 秒后投掷 ***";
CT_RABOSS_THADDIUS_THROWMSG_TIMER			= "投掷";
CT_RABOSS_THADDIUS_PVPDAMAGE_DETECT                = "^([^%s]+)[ ]*的[ ]*.+能量补充.+伤害。";
CT_RABOSS_THADDIUS_PVPDAMAGE_MSG                = "*** >>> %s <<< 电击队友 %s 人次 ***";


-- Instructor Razuvious
CT_RABOSS_RAZUVIOUS_INFO				= "当教官拉苏维奥斯施放瓦解怒吼时向团队发出警报。";
CT_RABOSS_RAZUVIOUS_STUDENT_NAME			= "见习死亡骑士";
CT_RABOSS_RAZUVIOUS_YELL1_DETECT			= "仁慈无用！";
CT_RABOSS_RAZUVIOUS_YELL2_DETECT			= "按我教导的去做！";
CT_RABOSS_RAZUVIOUS_YELL3_DETECT			= "绊腿……有什么问题么？";
CT_RABOSS_RAZUVIOUS_YELL4_DETECT			= "练习时间到此为止！都拿出真本事来！";
CT_RABOSS_RAZUVIOUS_SHOUT_DETECT			= "瓦解怒吼";
CT_RABOSS_RAZUVIOUS_DEATH_DETECT			= "教官拉苏维奥斯死亡了。";--见习死亡骑士获得了盾墙的效果。
CT_RABOSS_RAZUVIOUS_SHOUT_PREALERT			= "*** %s秒后施放瓦解怒吼！ ***";
CT_RABOSS_RAZUVIOUS_SHOUT_ALERT			= "*** 瓦解怒吼 - 25秒后再次施放  ***";

-- Gothik the Harvester 
CT_RABOSS_GOTHIK_INFO						= "收割者戈提克的各种技能时向团队发出警报。";
CT_RABOSS_GOTHIK_PHASE1_YELL1				= "你们这些蠢货已经主动步入了陷阱。";
CT_RABOSS_GOTHIK_PHASE2_YELL1				= "我已经等待很久了。现在你们将面对灵魂的收割者。";
CT_RABOSS_GOTHIK_INC						= "*** 收割者戈提克出现 ***";
CT_RABOSS_GOTHIK_INC_TIMER					= "进入房间";
CT_RABOSS_GOTHIK_TRAINEE		 			= "冷酷的学徒";
CT_RABOSS_GOTHIK_KNIGHT						= "冷酷的死亡骑士";
CT_RABOSS_GOTHIK_RIDER						= "冷酷的骑兵";
CT_RABOSS_GOTHIK_TRAINEES 					= "学徒 #%d";
CT_RABOSS_GOTHIK_KNIGHTS					= "死亡骑士 #%d";
CT_RABOSS_GOTHIK_RIDERS						= "骑兵 #%d";
CT_RABOSS_GOTHIK_KNIGHT_DEAD				= "*** 死亡骑士 死亡 ***";
CT_RABOSS_GOTHIK_RIDER_DEAD					= "*** 骑兵 死亡 ***";
CT_RABOSS_GOTHIK_ADD_INC 					= "*** 第%d波 %s 3秒内出现 ***";
CT_RABOSS_GOTHIK_ENGAGED					= "*** 戈提克战斗开始  ***";
CT_RABOSS_GOTHIK_1MINWARN					= "*** 1 分钟后戈提克出现 ***";
CT_RABOSS_GOTHIK_WARN						= "*** %s 分钟后戈提克出现  ***";
CT_RABOSS_GOTHIK_SECWARN					= "*** %s 秒后戈提克出现  ***";

-- FourHorsemen
CT_RABOSS_FOURHORSEMEN_INFO						= "显示四死亡骑士技能和印记计时";
CT_RABOSS_FOURHORSEMEN_MARK_ALERT				= "印记警报";
CT_RABOSS_FOURHORSEMEN_MARK_INFO				= "显示5秒印记警报";
CT_RABOSS_FOURHORSEMEN_ABILITY_ALERT			= "技能警报";
CT_RABOSS_FOURHORSEMEN_ABILITY_INFO				= "施放技能时显示警报";
CT_RABOSS_FOURHORSEMEN_THANE					= "库尔塔兹领主";
CT_RABOSS_FOURHORSEMEN_LADY						= "女公爵布劳缪克丝";
CT_RABOSS_FOURHORSEMEN_MOGRAINE					= "大领主莫格莱尼";
CT_RABOSS_FOURHORSEMEN_ZELIEK					= "瑟里耶克爵士";
CT_RABOSS_FOURHORSEMEN_ENGAGE_WARN				= "*** 四死亡骑士战斗开始 ***";
CT_RABOSS_FOURHORSEMEN_MARK_EXPR				= "受到了[ ]*([^%s]+)印记[ ]*效果的影响";
CT_RABOSS_FOURHORSEMEN_MARKTYPE1				= "莫格莱尼";
CT_RABOSS_FOURHORSEMEN_MARKTYPE2				= "库尔塔兹";
CT_RABOSS_FOURHORSEMEN_MARKTYPE3				= "布劳缪克丝";
CT_RABOSS_FOURHORSEMEN_MARKTYPE4				= "瑟里耶克";
CT_RABOSS_FOURHORSEMEN_MARK_ANNOUNCE			= "*** 印记(%d)  ***";
CT_RABOSS_FOURHORSEMEN_MARK_WARNING				= "*** 5秒后印记(%d) ***";
CT_RABOSS_FOURHORSEMEN_MARK_TIMER				= "印记 #%d";
CT_RABOSS_FOURHORSEMEN_METEOR_EXPR				= "^库尔塔兹领主[ ]*的[ ]*流星[ ]*击中";
CT_RABOSS_FOURHORSEMEN_METEOR_ANNOUNCE			= "*** 流星 ***";
CT_RABOSS_FOURHORSEMEN_METEOR_TIMER				= "流星";
CT_RABOSS_FOURHORSEMEN_HOLYWRATH_EXPR			= "^瑟里耶克爵士[ ]*的[ ]*神圣之怒[ ]*击中";
CT_RABOSS_FOURHORSEMEN_HOLYWRATH_ANNOUNCE		= "*** 神圣之怒 ***";
CT_RABOSS_FOURHORSEMEN_HOLYWRATH_TIMER			= "神圣之怒";
CT_RABOSS_FOURHORSEMEN_VOID_EXPR				= "^女公爵布劳缪克丝[ ]*施放了[ ]*虚空领域[ ]*。";
CT_RABOSS_FOURHORSEMEN_VOID_ANNOUNCE			= "*** 虚空领域 ***";
CT_RABOSS_FOURHORSEMEN_VOID_TIMER				= "虚空领域";
CT_RABOSS_FOURHORSEMEN_SHIELDWALL_EXPR			= "^([^%s]+)[ ]*获得了[ ]*盾墙[ ]*的效果。";
CT_RABOSS_FOURHORSEMEN_SHIELDWALL_ANNOUNCE		= "*** %s：盾墙20秒 ***";
CT_RABOSS_FOURHORSEMEN_SHIELDWALL_TIMER			= "盾墙：%s";
CT_RABOSS_FOURHORSEMEN_DPSGROUP_ALERT			= "跑位提示";
CT_RABOSS_FOURHORSEMEN_DPSGROUP_ALERT_INFO		= "提醒相应的DPS组到库尔塔兹领主和大领主莫格莱尼处";
CT_RABOSS_FOURHORSEMEN_DPSGROUP_THANE			= "第%d小队 -> 库尔塔兹领主";
CT_RABOSS_FOURHORSEMEN_DPSGROUP_MOGRAINE		= "第%d小队 -> 大领主莫格莱尼";
CT_RABOSS_FOURHORSEMEN_DPSGROUP_THANE_SELF		= "立刻移动到 库尔塔兹领主 处！";
CT_RABOSS_FOURHORSEMEN_DPSGROUP_MOGRAINE_SELF	= "立刻移动到 大领主莫格莱尼 处！";
CT_RABOSS_FOURHORSEMEN_DIE_EXP					= "^([^%s]+)[ ]*死亡了。";

-- Noth The Plaguebringer
CT_RABOSS_NOTH_INFO							= "当瘟疫使者诺斯发动心灵传送和闪现术时发出警报。";
CT_RABOSS_NOTH_CURSE_ALERT					= "瘟疫诅咒";
CT_RABOSS_NOTH_CURSE_ALERT_INFO				= "发出瘟疫诅咒警报。";
CT_RABOSS_NOTH_WARRIOR						= "瘟疫战士"
CT_RABOSS_NOTH_CHAMPION						= "瘟疫勇士";
CT_RABOSS_NOTH_GUARDIAN						= "瘟疫卫士";
CT_RABOSS_NOTH_YELL1						= "荣耀归于我主！";
CT_RABOSS_NOTH_YELL2						= "我要没收你的生命！";
CT_RABOSS_NOTH_YELL3						= "死吧，入侵者！";
CT_RABOSS_NOTH_SUMMON						= "起来吧，我的战士们！起来，再为主人尽忠一次！";
CT_RABOSS_NOTH_END							= "我要侍奉主人……到最后一刻！";
CT_RABOSS_NOTH_BACK_10SEC					= "*** 诺斯10秒后回到房间 ***";
CT_RABOSS_NOTH_BACK							= "*** 诺斯回来了- %s秒后再次上墙 ***"
CT_RABOSS_NOTH_ENGAGED						= "*** 诺斯战斗开始 - 90秒后上墙 ***"
CT_RABOSS_NOTH_TELEPORT_10SEC				= "*** 10秒后上墙 ***";
CT_RABOSS_NOTH_TELEPORTED					= "*** 诺斯上墙 - %s 秒重新出现 ***";
CT_RABOSS_NOTH_BLINKSTRING					= "瘟疫使者诺斯[ ]*获得了[ ]*闪现术[ ]*的效果。";
CT_RABOSS_NOTH_BLINKWARNING					= "*** 诺斯闪现 - 停止攻击！ ***";
CT_RABOSS_NOTH_BLINKSOON					= "*** 5秒后闪现 ***";
CT_RABOSS_NOTH_CURSESTRING					= "受到了[ ]*瘟疫使者的诅咒[ ]*效果的影响。";
CT_RABOSS_NOTH_DISPELL						= "*** 驱散诅咒 ***";
CT_RABOSS_NOTH_BLINK_TIMER					= "闪现";
CT_RABOSS_NOTH_INROOM_TIMER					= "上墙";
CT_RABOSS_NOTH_BACK_TIMER					= "回到房间";

-- Heigan the Unclean
CT_RABOSS_HEIGAN_INFO						= "当希尔盖的传送时向团队发出警报。";
CT_RABOSS_HEIGAN_PHASE1_YELL1				= "我看到你了……";
CT_RABOSS_HEIGAN_PHASE1_YELL2				= "你是我的了。";
CT_RABOSS_HEIGAN_PHASE1_YELL3				= "你……就是下一个。";
CT_RABOSS_HEIGAN_PHASE2_YELL1				= "你的生命正走向终结。";
CT_RABOSS_HEIGAN_DEAD						= "%s咽下了最后一口气。";
CT_RABOSS_HEIGAN_ENGAGED					= "*** 希尔盖战斗开始 - ~90 秒后传送 ***";
CT_RABOSS_HEIGAN_TELEPORTED					= "*** 希尔盖传送 - ~45 秒后再次出现 ***";
CT_RABOSS_HEIGAN_TELEPORT_10SEC				= "*** 10 秒后传送 ***";
CT_RABOSS_HEIGAN_TELEPORT_5SEC				= "*** 5 秒后传送 ***";
CT_RABOSS_HEIGAN_BACK_3SEC					= "*** 3 秒后希尔盖出现 ***";
CT_RABOSS_HEIGAN_BACK						= "*** 希尔盖出现 - ~90 秒后再次传送 ***";
CT_RABOSS_HEIGAN_TELEPORT_TIMER				= "传送";
CT_RABOSS_HEIGAN_DANCE						= "跳舞";
CT_RABOSS_HEIGAN_ERUPTION_TIMER				= "熔岩爆发 #%d";

-- Loatheb
CT_RABOSS_LOATHEB_BOSSNAME					= "洛欧塞布";
CT_RABOSS_LOATHEB_INFO						= "当洛欧塞布发动必然的厄运时向团队发出警报。";
CT_RABOSS_LOATHEB_HEAL_RAID_ALERT			= "通告治疗";
CT_RABOSS_LOATHEB_HEAL_RAID_INFO			= "在团队频道中通告下一个治疗（需要团队领袖或助理权限）。"
CT_RABOSS_LOATHEB_HEAL_WHISPER_ALERT		= "密语通告";
CT_RABOSS_LOATHEB_HEAL_WHISPER_INFO			= "密语通告治疗（需要团队领袖或助理权限）。"
CT_RABOSS_LOATHEB_SPORE_ALERT				= "孢子警告";
CT_RABOSS_LOATHEB_SPORE_ALERT_INFO			= "孢子刷新警告，提醒相应的小组"
CT_RABOSS_LOATHEB_ENGAGE					= "*** 2 分钟后发动必然的厄运 ***";
CT_RABOSS_LOATHEB_DOOM_STRING				= "受到了[ ]*必然的厄运[ ]*效果的影响。";
CT_RABOSS_LOATHEB_DOOM_5SEC					= "*** 5 秒后发动必然的厄运 ***";
CT_RABOSS_LOATHEB_DOOM_WARN					= "*** 必然的厄运 ***";
CT_RABOSS_LOATHEB_DOOM_TIMER				= "必然的厄运 %d";
CT_RABOSS_LOATHEB_POTION_WARNING			= "药水提醒";
CT_RABOSS_LOATHEB_POTION_WARNING_INFO		= "提醒使用必要的治疗和暗抗物品";
CT_RABOSS_LOATHEB_SHADOW_POTION				= "强效暗影防护药水";
CT_RABOSS_LOATHEB_BANDAGE					= "厚符文布绷带";
CT_RABOSS_LOATHEB_WHIPPER					= "鞭根块茎";
CT_RABOSS_LOATHEB_STONE						= "强效治疗石";
CT_RABOSS_LOATHEB_DECURSE_STRING			= "洛欧塞布[ ]*对[ ]*洛欧塞布[ ]*施放了[ ]*移处诅咒[ ]*。";
CT_RABOSS_LOATHEB_DECURSE_TIMER				= "移处诅咒";
CT_RABOSS_LOATHEB_SPORE_STRING				= "洛欧塞布[ ]*施放了[ ]*召唤孢子[ ]*。";
CT_RABOSS_LOATHEB_SPORE_TIMER				= "召唤孢子 %d";
CT_RABOSS_LOATHEB_SPORE_3SEC				= "*** 3 秒后刷新孢子，第 %d 小队准备 ***";
CT_RABOSS_LOATHEB_SPORE_WARN				= "*** 孢子即将刷新，注意观察四周 ***";
CT_RABOSS_LOATHEB_SPORE_SPAWN				= "*** 孢子出现，立刻赶往刷新点 ***";
CT_RABOSS_LOATHEB_HEAL_SETUP				= "设置治疗顺序"
CT_RABOSS_LOATHEB_NO_BC_INFO				= "你不是团队领袖或助理，你所做的改动将不会被同步。";
CT_RABOSS_LOATHEB_NO_CD						= "就绪";
CT_RABOSS_LOATHEB_SET_HEAL_ROTATION			= "保存并同步";
CT_RABOSS_LOATHEB_SET_HEAL_ROTATION_NO_BC	= "保存";
CT_RABOSS_LOATHEB_HEAL_WARNING				= "治疗 #%s 完成 - 下一位：%s";
CT_RABOSS_LOATHEB_YOU_ARE_NEXT				= "你是下一个治疗！";
CT_RABOSS_LOATHEB_YOU_ARE_SOON				= "准备治疗！";
CT_RABOSS_LOATHEB_HEAL_STRING				= "^([^%s]+)[ ]*受到了[ ]*堕落心灵[ ]*效果的影响。";
CT_RABOSS_LOATHEB_LOCK						= "锁定窗口";
CT_RABOSS_LOATHEB_UNLOCK					= "解锁窗口";
CT_RABOSS_LOATHEB_CLOSE						= "关闭";
CT_RABOSS_LOATHEB_CMD_UNKNOWN				= "有效命令：/loatheb show/hide/config/setup/broadcast/bc/undelete";

--Sapphiron
CT_RABOSS_SAPPHIRON_INFO					= "寒冰炸弹、生命吸取和狂暴警告";
CT_RABOSS_SAPPHIRON_RANGECHECK				= "距离检查";
CT_RABOSS_SAPPHIRON_ENGAGE_DETECT			= "^你受到了[ ]*冰霜光环[ ]*效果的影响。$";
CT_RABOSS_SAPPHIRON_ENGAGE_ANNOUNCE			= "*** 萨菲隆战斗开始 ***";
CT_RABOSS_SAPPHIRON_ICEBLOCK_ANNOUNCE		= "我中了冰箱，站到我身后！";
CT_RABOSS_SAPPHIRON_FROSTBOLT_HIT_EXPR		= "^萨菲隆[ ]*的[ ]*寒冰箭[ ]*击中";
CT_RABOSS_SAPPHIRON_FROSTBOLT_GAIN_EXPR		= "^你受到了[ ]*寒冰箭[ ]*效果的影响。$";
CT_RABOSS_SAPPHIRON_FROSTBOLT_FADE_EXPR		= "^寒冰箭[ ]*效果从你身上消失了。$";
CT_RABOSS_SAPPHIRON_FROSTAURA_EXPR			= "萨菲隆[ ]*的[ ]*冰霜光环";
CT_RABOSS_SAPPHIRON_LIFEDRAIN_ALERT			= "生命吸取警报";
CT_RABOSS_SAPPHIRON_LIFEDRAIN_ALERT_INFO	= "生命吸取警报和预警";
CT_RABOSS_SAPPHIRON_LIFEDRAIN_EXPR1			= "受到了[ ]*生命吸取";
CT_RABOSS_SAPPHIRON_LIFEDRAIN_EXPR2			= "生命吸取[ ]*被.+抵抗";
CT_RABOSS_SAPPHIRON_LIFEDRAIN_ANNOUNCE		= "*** 生命吸取 - ~24秒后再次施放! ***";
CT_RABOSS_SAPPHIRON_LIFEDRAIN_WARN			= "***  %d秒后生命吸取 ***";
CT_RABOSS_SAPPHIRON_LIFEDRAIN_TIMER			= "生命吸取";
CT_RABOSS_SAPPHIRON_DEEPBREATH_EXPR			= "%s深深地吸了一口气……";
CT_RABOSS_SAPPHIRON_DEEPBREATH_ANNOUNCE		= "*** 冰霜吐息7秒后降临 ***";
CT_RABOSS_SAPPHIRON_DEEPBREATH_TIMER		= "冰霜吐息";
CT_RABOSS_SAPPHIRON_ENRAGE_ANNOUNCE			= "*** %d 秒后狂暴 ***";
CT_RABOSS_SAPPHIRON_ENRAGE_TIMER			= "狂暴";
CT_RABOSS_SAPPHIRON_FLY_TIMER				= "升空";

-- Kel'Thuzad
CT_RABOSS_KELTHUZAD_INFO					= "克尔苏加德每阶段警报";
CT_RABOSS_KELTHUZAD_TELL					= "密语警报";
CT_RABOSS_KELTHUZAD_TELL_INFO				= "发送一条密语警报给中了自爆法力的玩家";
CT_RABOSS_KELTHUZAD_RANGECHECK				= "距离检查";
CT_RABOSS_KELTHUZAD_HIDELOCALALERT			= "隐藏本地通知";
CT_RABOSS_KELTHUZAD_HIDELOCALALERT_INFO		= "隐藏第二三阶段在屏幕中下部分显示的各种技能警报";
CT_RABOSS_KELTHUZAD_FROSTBOLT				= "冰霜箭警报";
CT_RABOSS_KELTHUZAD_FROSTBOLT_INFO			= "单体冰霜箭警报和计时";
CT_RABOSS_KELTHUZAD_PHASE1_EXPR				= "仆从们，侍卫们，隶属于黑暗与寒冷的战士们！听从克尔苏加德的召唤！";
CT_RABOSS_KELTHUZAD_PHASE1_ANNOUNCE			= "*** 第一阶段 ***";
CT_RABOSS_KELTHUZAD_PHASE1_TIMER			= "第二阶段";
CT_RABOSS_KELTHUZAD_PHASE2_EXPR1			= "祈祷我的慈悲吧！";
CT_RABOSS_KELTHUZAD_PHASE2_EXPR2			= "你的末日临近了！";
CT_RABOSS_KELTHUZAD_PHASE2_EXPR3			= "祈祷我的慈悲吧！";
CT_RABOSS_KELTHUZAD_PHASE2_EXPR4			= "呼出你的最后一口气！";
CT_RABOSS_KELTHUZAD_PHASE2_ANNOUNCE			= "*** 第二阶段 - 克尔苏加德激活 ***";
CT_RABOSS_KELTHUZAD_PHASE2_TIMER			= "克尔苏加德激活";
CT_RABOSS_KELTHUZAD_PHASE3_EXPR				= "主人，我需要帮助！";
CT_RABOSS_KELTHUZAD_PHASE3_ANNOUNCE			= "*** 第三阶段 - 寒冰皇冠卫士10秒后出现 ***";
CT_RABOSS_KELTHUZAD_END_EXPR				= "啊！别……高兴得……太早了！你们的胜利空洞而虚无，没有任何意义，我很快就将卷土重来！";
CT_RABOSS_KELTHUZAD_MC_EXPR1				= "你的灵魂现在属于我了！";
CT_RABOSS_KELTHUZAD_MC_EXPR2				= "没有人能逃得掉！";
CT_RABOSS_KELTHUZAD_MC_ANNOUNCE				= "*** 精神控制 ***";
CT_RABOSS_KELTHUZAD_MC_PREALERT				= "*** 8秒后随时可能精神控制 - 改用魔杖或射箭 ***";
CT_RABOSS_KELTHUZAD_MC_TIMER				= "精神控制";
CT_RABOSS_KELTHUZAD_MCEND_TIMER				= "精神控制结束";
CT_RABOSS_KELTHUZAD_GUARDIAN_EXPR			= "很好，冰荒废土的战士们，起来吧！我命令你们为主人而战斗，杀戮，直到死亡！一个活口都不要留！";
CT_RABOSS_KELTHUZAD_GUARDIAN_ANNOUNCE		= "*** 10 秒后寒冰皇冠卫士出现 ***";
CT_RABOSS_KELTHUZAD_GUARDIAN_TIMER			= "寒冰皇冠卫士";
CT_RABOSS_KELTHUZAD_FISSURE_EXPR			= "^克尔苏加德[ ]*施放了[ ]*暗影裂隙[ ]*。";
CT_RABOSS_KELTHUZAD_FISSURE_ANNOUNCE		= "*** 暗影裂隙 ***";
CT_RABOSS_KELTHUZAD_FROSTBLAST_EXPR			= "^([^%s]+)[ ]*受到了[ ]*冰霜冲击[ ]*效果的影响。";
CT_RABOSS_KELTHUZAD_FROSTBLAST_ANNOUNCE		= "*** 冰霜冲击 ***";
CT_RABOSS_KELTHUZAD_FROSTBLAST_PREALERT		= "*** 5秒后可能冰霜冲击 - 近战速退 ***";
CT_RABOSS_KELTHUZAD_FROSTBLAST_TIMER		= "冰霜冲击";
CT_RABOSS_KELTHUZAD_FROSTBOLT_SINGLE_EXPR	= "^克尔苏加德[ ]*开始施放[ ]*冰霜箭[ ]*。";
CT_RABOSS_KELTHUZAD_FROSTBOLT_SINGLE_WARN	= "*** 冰霜箭 (%d) - 立刻打断！ ***";
CT_RABOSS_KELTHUZAD_FROSTBOLT_SINGLE_TIMER	= "冰霜箭";
CT_RABOSS_KELTHUZAD_INTERRUPT_EXPR			= "^([^%s]+)[ ]*打断了[ ]*克尔苏加德[ ]*的[ ]*冰霜箭[ ]*。";
CT_RABOSS_KELTHUZAD_INTERRUPT_ANNOUNCE		= "*** 冰霜箭 (%d)被 %s 打断！ ***";
CT_RABOSS_KELTHUZAD_FROSTBOLT_MULTI_EXPR	= "^克尔苏加德[ ]*的[ ]*冰霜箭[ ]*击中.+造成[ ]*(%d+)[ ]*点[ ]*冰霜[ ]*伤害。";
CT_RABOSS_KELTHUZAD_FROSTBOLT_MULTI_TIMER	= "群体冰霜箭";
CT_RABOSS_KELTHUZAD_DETONATE_EXPR			= "^([^%s]+)[ ]*受到了[ ]*自爆法力[ ]*效果的影响。";
CT_RABOSS_KELTHUZAD_DETONATE_ANNOUNCE		= "*** 自爆法力 - %s ***";
CT_RABOSS_KELTHUZAD_DETONATE_SELFWARN		= "你是炸弹！";
CT_RABOSS_KELTHUZAD_DETONATE_TIMER			= "自爆法力";
CT_RABOSS_KELTHUZAD_DETONATE_WHISPER		= "你是炸弹！和队友保持10码以上距离！";