if (GetLocale() == "zhCN") then

AtlasLoot_LootTypes = { "东部王国副本", "卡利姆多副本", "户外团队作战", "套装", "阵营", "PvP" };

AtlasLoot_Zones = {
    { 
        { "黑石深渊", "" },
        { "黑石塔 (下层)", "" },
        { "黑石塔 (上层)", "" },
        { "黑翼之巢", "" },
        { "死亡矿井", "" },
        { "诺莫瑞根", "" },
        { "熔火之心", "" },
        { "纳克萨玛斯", "" },
        { "血色修道院", "" },
        { "通灵学院", "" },
        { "影牙城堡", "" },
        { "监狱", "" },
        { "斯坦索姆", "" },
        { "阿塔哈卡神庙", "" },
        { "奥达曼", "" },
        { "祖尔格拉布", "" },
    },
    {
        { "黑暗深渊", "" },
        { "厄运之槌 (东区)", "" },
        { "厄运之槌 (北区)", "" },
        { "厄运之槌 (西区)", "" },
        { "玛拉顿", "" },
        { "奥妮克希亚的巢穴", "" },
        { "怒焰裂谷", "" },
        { "剃刀高地", "" },
        { "剃刀沼泽", "" },
        { "安其拉废墟", "" },
        { "安其拉神殿", "" },
        { "哀嚎洞穴", "" },
        { "祖尔法拉克", "" },
    },
    {
        { "艾索雷葛斯", "AAzuregos" },
        { "艾莫莉丝", "DEmeriss" },
        { "卡扎克", "KKazzak" },
        { "莱索恩", "DLethon"},
        { "泰拉尔", "DTaerar" },
        { "伊森德雷", "DYsondre" },
    },
    {
        { "PvP 套装", "" },
        { "安其拉废墟职业套装", "" },
        { "安其拉神殿职业套装", "" },
        { "T0/T0.5 套装", "" },
        { "T1 套装", "" },
        { "T2 套装", "" },
        { "T3 套装", "" },
        { "祖尔格拉布职业套装", "" },
    },
    {
        { "银色黎明", "" },
        { "诺兹多姆的子嗣", "AQBroodRings" },
        { "塞纳里奥议会", "" },
        { "暗月马戏团", "Darkmoon" },
        { "瑟银兄弟会", "" },
        { "木喉要塞", "Timbermaw" },
        { "赞达拉部族", "" },
        { "传说武器", "Legendaries" },
        { "世界掉落", "" },
    },
    {
        { "奥特兰克山谷", "" },
        { "阿拉希盆地", "" },
        { "PvP 套装", "" },
        { "战歌峡谷", "" },
    },
};

AtlasLoot_Bosses = {
    ["黑暗深渊"] = {
        { "加摩拉", "BFDGhamoora" },
        { "萨利维丝", "BFDLadySarevess" },
        { "格里哈斯特", "BFDGelihast" },
        { "阿奎尼斯男爵", "BFDBaronAquanis" },
        { "梦游者克尔里斯", "BFDTwilightLordKelris" },
        { "瑟拉吉斯", "BFDOldSerrakis" },
        { "阿库迈尔", "BFDAkumai" },
        { "小怪掉落", "BFDTrash" },
    },
    ["黑石深渊"] = {
        { "洛考尔", "BRDLordRoccor" },
        { "审讯官格斯塔恩", "BRDHighInterrogatorGerstahn" },
        { "法律之环，塞尔德林", "BRDArena" },
        { "驯犬者格雷布玛尔", "BRDHoundmaster" },
        { "控火师罗格雷恩 (稀有)", "BRDPyromantLoregrain" },
        { "黑色宝库", "BRDWarderStilgiss" },
        { "弗诺斯·达克维尔", "BRDFineousDarkvire" },
        { "伊森迪奥斯", "BRDLordIncendius" },
        { "贝尔加", "BRDBaelGar" },
        { "安格弗将军", "BRDGeneralAngerforge" },
        { "傀儡统帅阿格曼奇", "BRDGolemLordArgelmach" },
        { "黑铁酒吧", "BRDGuzzler" },
        { "弗莱拉斯大使", "BRDFlamelash" },
        { "无敌的潘佐尔 (稀有)", "BRDPanzor" },
        { "召唤者之墓", "BRDTomb" },
        { "玛格姆斯", "BRDMagmus" },
        { "达格兰·索瑞森大帝", "BRDImperatorDagranThaurissan" },
        { "铁炉堡公主茉艾拉·铜须", "BRDPrincess" },
        { "小怪掉落", "BRDTrash" },
    },
    ["黑石塔 (下层)"] = {
        { "欧莫克大王", "LBRSOmokk" },
        { "尖石统帅 (稀有)", "LBRSSpirestoneLord" },
        { "暗影猎手沃什加斯", "LBRSVosh" },
        { "指挥官沃恩", "LBRSVoone" },
        { "莫尔·灰蹄", "LBRSGrayhoof" },
        { "烟网蛛后", "LBRSSmolderweb" },
        { "水晶之牙 (稀有)", "LBRSCrystalFang" },
        { "乌洛克", "LBRSDoomhowl" },
        { "军需官兹格雷斯", "LBRSZigris" },
        { "奴役者基兹鲁尔", "LBRSSlavener" },
        { "哈雷肯", "LBRSHalycon" },
        { "维姆萨拉克", "LBRSWyrmthalak" },
        { "班诺克·巨斧 (稀有)", "LBRSGrimaxe" },
        { "尖石屠夫 (稀有)", "LBRSSpirestoneButcher" },
        { "小怪掉落", "LBRSTrash" },
    },
    ["黑石塔 (上层)"] = {
        { "烈焰卫士艾博希尔", "UBRSEmberseer" },
        { "索拉卡·火冠", "UBRSSolakar" },
        { "烈焰之父", "UBRSFLAME" },
        { "杰德 (稀有)", "UBRSRunewatcher" },
        { "古拉鲁克", "UBRSAnvilcrack" },
        { "大酋长雷德·黑手", "UBRSRend" },
        { "盖斯", "UBRSGyth" },
        { "比斯巨兽", "UBRSBeast" },
        { "瓦塔拉克公爵", "UBRSValthalak" },
        { "达基萨斯将军", "UBRSDrakkisath" },
        { "小怪掉落", "UBRSTrash" },
    },
    ["黑翼之巢"] = {
        { "狂野的拉佐格尔", "BWLRazorgore" },
        { "堕落的瓦拉斯塔兹", "BWLVaelastrasz" },
        { "勒什雷尔", "BWLLashlayer" },
        { "费尔默", "BWLFiremaw" },
        { "埃博诺克", "BWLEbonroc" },
        { "弗莱格尔", "BWLFlamegor" },
        { "克洛玛古斯", "BWLChromaggus" },
        { "奈法利安", "BWLNefarian" },
        { "小怪掉落", "BWLTrashMobs" },
    },
    ["死亡矿井"] = {
        { "拉克佐", "VCRhahkZor" },
        { "矿工约翰森 (稀有)", "VCMinerJohnson" },
        { "斯尼德", "VCSneed" },
        { "基尔尼格", "VCGilnid" },
        { "绿皮队长", "VCCaptainGreenskin" },
        { "艾德温·范克利夫", "VCVanCleef" },
        { "重拳先生", "VCMrSmite" },
        { "曲奇", "VCCookie" },
        { "套装: 迪菲亚皮甲", "VCDefiasSET" },
    },
    ["厄运之槌 (东区)"] = {
        { "普希林", "DMEPusillin" },
        { "瑟雷姆·刺蹄", "DMEZevrimThornhoof" },
        { "海多斯博恩", "DMEHydro" },
        { "雷瑟塔帝丝", "DMELethtendris" },
        { "奥兹恩", "DMEAlzzin" },
        { "伊萨莉恩", "DMEIsalien" },
        { "小怪掉落", "DMETrash" },
        { "厄运之槌任务书", "DMBooks" },
    },
    ["厄运之槌 (北区)"] = {
        { "卫兵摩尔达", "DMNGuardMoldar" },
        { "践踏者克雷格", "DMNStomperKreeg" },
        { "卫兵芬古斯", "DMNGuardFengus" },
        { "诺特·希姆加可", "DMNThimblejack" },
        { "卫兵斯里基克", "DMNGuardSlipkik" },
        { "克罗卡斯", "DMNCaptainKromcrush" },
        { "戈多克大王", "DMNKingGordok" },
        { "贡品", "DMNTRIBUTERUN" },
        { "厄运之槌任务书", "DMBooks" },
    },
    ["厄运之槌 (西区)"] = {
        { "特迪斯·扭木", "DMWTendrisWarpwood" },
        { "伊琳娜·暗木", "DMWIllyannaRavenoak" },
        { "卡雷迪斯镇长", "DMWMagisterKalendris" },
        { "苏斯 (稀有)", "DMWTsuzee" },
        { "伊莫塔尔", "DMWImmolthar" },
        { "赫尔努拉斯", "DMWHelnurath" },
        { "托塞德林王子", "DMWPrinceTortheldrin" },
        { "小怪掉落", "DMWTrash" },
        { "厄运之槌任务书", "DMBooks" },
    },
    ["诺莫瑞根"] = {
        { "粘性辐射尘", "GnViscousFallout" },
        { "格鲁比斯", "GnGrubbis" },
        { "电刑器6000型", "GnElectrocutioner6000" },
        { "麦克尼尔·瑟玛普拉格", "GnMekgineerThermaplugg" },
        { "黑铁大师 (稀有)", "GnDIAmbassador" },
        { "群体打击者9-60", "GnCrowdPummeler960" },
        { "小怪掉落", "GnTrash" },
    },
    ["玛拉顿"] = {
        { "诺克赛恩", "MaraNoxxion" },
        { "锐刺鞭笞者", "MaraRazorlash" },
        { "维利塔恩", "MaraLordVyletongue" },
        { "收割者麦什洛克 (稀有)", "MaraMeshlok" },
        { "被诅咒的塞雷布拉斯", "MaraCelebras" },
        { "兰斯利德", "MaraLandslide" },
        { "工匠吉兹洛克", "MaraTinkererGizlock" },
        { "洛特格里普", "MaraRotgrip" },
        { "瑟莱德丝公主", "MaraPrincessTheradras" },
    },
    ["熔火之心"] = {
        { "鲁西弗隆", "MCLucifron" },
        { "玛格曼达", "MCMagmadar" },
        { "基赫纳斯", "MCGehennas" },
        { "加尔", "MCGarr" },
        { "沙斯拉尔", "MCShazzrah" },
        { "迦顿男爵", "MCGeddon" },
        { "焚化者古雷曼格", "MCGolemagg" },
        { "萨弗隆先驱者", "MCSulfuron" },
        { "管理者埃克索图斯", "MCMajordomo" },
        { "拉格纳罗斯", "MCRagnaros" },
        { "小怪掉落", "MCTrashMobs" },
        { "BOSS随机掉落", "MCRANDOMBOSSDROPPS" },
    },
    ["纳克萨玛斯"] = {
        { "帕奇维克", "NAXPatchwerk" },
        { "格罗布鲁斯", "NAXGrobbulus" },
        { "格拉斯", "NAXGluth" },
        { "塔迪乌斯", "NAXThaddius" },
        { "阿努布雷坎", "NAXAnubRekhan" },
        { "黑女巫法琳娜", "NAXGrandWidowFaerlina" },
        { "迈克斯纳", "NAXMaexxna" },
        { "教官拉苏维奥斯", "NAXInstructorRazuvious" },
        { "收割者戈提克", "NAXGothikderHarvester" },
        { "天启四骑士", "NAXTheFourHorsemen" },
        { "瘟疫使者诺斯", "NAXNothderPlaguebringer" },
        { "肮脏的希尔盖", "NAXHeiganderUnclean" },
        { "洛欧塞布", "NAXLoatheb" },
        { "萨菲隆", "NAXSapphiron" },
        { "克尔苏加德", "NAXKelThuzard" },
        { "小怪掉落", "NAXTrash" },
    },
    ["奥妮克希亚的巢穴"] = {
        { "奥妮克希亚", "Onyxia" },
    },
    ["怒焰裂谷"] = {
        { "饥饿者塔拉加曼", "RFCTaragaman" },
        { "祈求者耶戈什", "RFCJergosh" },
    },
    ["剃刀高地"] = {
        { "图特卡什", "RFDTutenkash" },
        { "火眼莫德雷斯", "RFDMordreshFireEye" },
        { "暴食者", "RFDGlutton" },
        { "拉戈斯诺特 (稀有)", "RFDRagglesnout" },
        { "寒冰之王亚门纳尔", "RFDAmnennar" },
        { "小怪掉落", "RFDTrash" },
    },
    ["剃刀沼泽"] = {
        { "亡语者贾格巴", "RFKDeathSpeakerJargba" },
        { "主宰拉姆塔斯", "RFKOverlordRamtusk" },
        { "暴怒的阿迦赛罗斯", "RFKAgathelos" },
        { "盲眼猎手 (稀有)", "RFKBlindHunter" },
        { "卡尔加·刺肋", "RFKCharlgaRazorflank" },
        { "唤地者哈穆加 (稀有)", "RFKEarthcallerHalmgar" },
        { "小怪掉落", "RFKTrash" },
    },
    ["安其拉废墟"] = {
        { "库林纳克斯", "AQ20Kurinnaxx" },
        { "安多洛夫中将", "AQ20Andorov" },
        { "将军的随从", "AQ20CAPTIAN" },
        { "拉贾克斯将军", "AQ20Rajaxx" },
        { "莫阿姆", "AQ20Moam" },
        { "吞咽者布鲁", "AQ20Buru" },
        { "狩猎者阿亚米斯", "AQ20Ayamiss" },
        { "无疤者奥斯里安", "AQ20Ossirian" },
        { "职业技能书", "AQ20ClassBooks" },
        { "安其拉附魔公式", "AQEnchants" },
    },
    ["血色修道院"] = {
        { "驯犬者洛克希", "SMHoundmasterLoksey" },
        { "奥法师杜安", "SMDoan" },
        { "赫洛德", "SMHerod" },
        { "大检察官法尔班克斯", "SMFairbanks" },
        { "血色十字军指挥官莫格莱尼", "SMMograine" },
        { "大检察官怀特迈恩", "SMWhitemane" },
        { "铁脊死灵 (稀有)", "SMIronspine" },
        { "永醒的艾希尔 (稀有)", "SMAzshir" },
        { "死灵勇士 (稀有)", "SMFallenChampion" },
        { "血法师萨尔诺斯", "SMBloodmageThalnos" },
        { "小怪掉落", "SMTrash" },
        { "套装: 血色十字军链甲", "SMScarletSET" },
    },
    ["通灵学院"] = {
        { "基尔图诺斯的卫士",  "SCHOLOBloodSteward" },
        { "传令官基尔图诺斯", "SCHOLOKirtonostheHerald" },
        { "詹迪斯·巴罗夫", "SCHOLOJandiceBarov" },
        { "血骨傀儡", "SCHOLORattlegore" },
        { "死亡骑士达克雷尔", "SCHOLODeathKnight" },
        { "马杜克·布莱克波尔", "SCHOLOMarduk" },
        { "维克图斯", "SCHOLOVectus" },
        { "莱斯·霜语", "SCHOLORasFrostwhisper" },
        { "库尔莫克", "SCHOLOKormok" },
        { "讲师玛丽希亚", "SCHOLOInstructorMalicia" },
        { "瑟尔林·卡斯迪诺夫教授", "SCHOLODoctorTheolenKrastinov" },
        { "博学者普克尔特", "SCHOLOLorekeeperPolkelt" },
        { "拉文尼亚", "SCHOLOTheRavenian" },
        { "阿雷克斯·巴罗夫", "SCHOLOLordAlexeiBarov" },
        { "伊露希亚·巴罗夫", "SCHOLOLadyIlluciaBarov" },
        { "黑暗院长加丁", "SCHOLODarkmasterGandling" },
        { "小怪掉落", "SCHOLOTrash" },
    },
    ["影牙城堡"] = {
        { "屠夫拉佐克劳", "BSFRazorclawtheButcher" },
        { "席瓦莱恩男爵", "BSFSilverlaine" },
        { "指挥官斯普林瓦尔", "BSFSpringvale" },
        { "盲眼守卫奥杜", "BSFOdotheBlindwatcher" },
        { "吞噬者芬鲁斯", "BSFFenrustheDevourer" },
        { "狼王南杜斯", "BSFWolfMasterNandos" },
        { "大法师阿鲁高", "BSFArchmageArugal" },
        { "小怪掉落", "BSFTrash" },
    },
    ["监狱"] = {
        { "卡姆·深怒", "SWStKamDeepfury" },
        { "布鲁高·铁拳", "SWStBruegalIronknuckle" },
    },
    ["斯坦索姆"] = {
        { "斯库尔 (稀有)", "STRATSkull" },
        { "斯坦索姆信使", "STRATStratholmeCourier" },
        { "弗拉斯·希亚比", "STRATFrasSiabi" },
        { "弗雷斯特恩", "STRATHearthsingerForresten" },
        { "不可宽恕者", "STRATTheUnforgiven" },
        { "悲惨的提米", "STRATTimmytheCruel" },
        { "炮手威利", "STRATCannonMasterWilley" },
        { "档案管理员加尔福特", "STRATArchivistGalford" },
        { "巴纳扎尔", "STRATBalnazzar" },
        { "亚雷恩和索托斯", "STRATSothosJarien" },
        { "石脊 (稀有)", "STRATStonespine" },
        { "安娜丝塔丽男爵夫人", "STRATBaronessAnastari" },
        { "奈鲁布恩坎", "STRATNerubenkan" },
        { "苍白的玛勒基", "STRATMalekithePallid" },
        { "巴瑟拉斯镇长", "STRATMagistrateBarthilas" },
        { "吞咽者拉姆斯登", "STRATRamsteintheGorger" },
        { "瑞文戴尔男爵", "STRATBaronRivendare" },
        { "小怪掉落", "STRATTrash" },
    },
    ["阿塔哈卡神庙"] = {
        { "巨魔小首领", "STTrollMinibosses" },
        { "阿塔拉利恩", "STAtalalarion" },
        { "德姆赛卡尔", "STDreamscythe" },
        { "德拉维沃尔", "STWeaver"},
        { "哈卡的化身", "STAvatarofHakkar" },
        { "预言者迦玛兰", "STJammalan" },
        { "可悲的奥戈姆", "STOgom" },
        { "摩弗拉斯", "STMorphaz" },
        { "哈扎斯", "STHazzas" },
        { "伊兰尼库斯的阴影", "STEranikus" },
        { "小怪掉落", "STTrash" },
    },
    ["安其拉神殿"] = {
        { "安其拉神殿", "AQ40Skeram" },
        { "维姆", "AQ40Vem" },
        { "亚尔基公主", "AQ40Yauj" },
        { "克里勋爵", "AQ40Kri" },
        { "沙尔图拉", "AQ40Sartura" },
        { "顽强的范克瑞斯", "AQ40Fankriss" },
        { "维希度斯", "AQ40Viscidus" },
        { "哈霍兰公主", "AQ40Huhuran" },
        { "维克尼拉斯大帝", "AQ40Veknilash" },
        { "维克洛尔大帝", "AQ40Veklor" },
        { "奥罗", "AQ40Ouro" },
        { "克苏恩", "AQ40CThun" },
        { "小怪掉落", "AQ40Trash" },
        { "安其拉附魔公式", "AQEnchants" },
        { "安其拉开门任务奖励", "AQOpening" },
    },
    ["奥达曼"] = {
        { "鲁维罗什", "UldRevelosh" },
        { "艾隆纳亚", "UldIronaya" },
        { "古代的石头看守者", "UldAncientStoneKeeper" },
        { "加加恩·火锤", "UldGalgannFirehammer" },
        { "格瑞姆洛克", "UldGrimlok" },
        { "阿扎达斯", "UldArchaedas" },
        { "小怪掉落", "UldTrash" },
    },
    ["哀嚎洞穴"] = {
        { "考布莱恩", "WCLordCobrahn" },
        { "安娜科德拉", "WCLadyAnacondra" },
        { "克雷什", "WCKresh" },
        { "皮萨斯", "WCLordPythas" },
        { "斯卡姆", "WCSkum" },
        { "瑟芬迪斯", "WCLordSerpentis" },
        { "永生者沃尔丹", "WCVerdan" },
        { "吞噬者穆坦努斯", "WCMutanus" },
        { "变异精灵龙 (稀有)", "WCDeviateFaerieDragon" },
        { "套装: 毒蛇的拥抱", "WCViperSET" },
    },
    ["祖尔法拉克"] = {
        { "安图苏尔", "ZFAntusul" },
        { "巫医祖穆拉恩", "ZFWitchDoctorZumrah" },
        { "暗影祭司塞瑟斯", "ZFSezzziz" },
        { "加兹瑞拉", "ZFGahzrilla" },
        { "灰尘怨灵 (稀有)", "ZFDustwraith" },
        { "乌克兹·沙顶", "ZFChiefUkorzSandscalp" },
        { "泽雷利斯 (稀有)", "ZFZerillis" },
        { "小怪掉落", "ZFTrash" },
    },
    ["祖尔格拉布"] = {
        { "高阶祭司耶克里克", "ZGJeklik" },
        { "高阶祭司温诺西斯", "ZGVenoxis" },
        { "高阶祭司玛尔里", "ZGMarli" },
        { "血领主曼多基尔", "ZGMandokir" },
        { "格里雷克，钢铁之血", "ZGGrilek" },
        { "哈扎拉尔，织梦者", "ZGHazzarah" },
        { "雷纳塔基，千刃之王", "ZGRenataki" },
        { "雷巫乌苏雷", "ZGWushoolay" },
        { "加兹兰卡", "ZGGahzranka" },
        { "高阶祭司塞卡尔", "ZGThekal" },
        { "高阶祭司娅尔罗", "ZGArlokk" },
        { "妖术师金度", "ZGJindo" },
        { "哈卡", "ZGHakkar" },
        { "BOSS随机掉落", "ZGShared" },
        { "小怪掉落", "ZGTrash" },
        { "祖尔格拉布附魔", "ZGEnchants" },
    },
    ["PvP 套装"] = {
        { "德鲁伊", "PVPDruid" },
        { "猎人", "PVPHunter" },
        { "法师", "PVPMage" },
        { "圣骑士", "PVPPaladin" },
        { "牧师", "PVPPriest" },
        { "盗贼", "PVPRogue" },
        { "萨满祭司", "PVPShaman" },
        { "术士", "PVPWarlock" },
        { "战士", "PVPWarrior" },
        { "武器 1", "PVPWeapons1" },
        { "武器 2", "PVPWeapons2" },
    },
    ["安其拉废墟职业套装"] = {
        { "德鲁伊", "AQ20Druid" },
        { "猎人", "AQ20Hunter" },
        { "法师", "AQ20Mage" },
        { "圣骑士", "AQ20Paladin" },
        { "牧师", "AQ20Priest" },
        { "盗贼", "AQ20Rogue" },
        { "萨满祭司", "AQ20Shaman" },
        { "术士", "AQ20Warlock" },
        { "战士", "AQ20Warrior" },
    },
    ["安其拉神殿职业套装"] = {
        { "德鲁伊", "AQ40Druid" },
        { "猎人", "AQ40Hunter" },
        { "法师", "AQ40Mage" },
        { "圣骑士", "AQ40Paladin" },
        { "牧师", "AQ40Priest" },
        { "盗贼", "AQ40Rogue" },
        { "萨满祭司", "AQ40Shaman" },
        { "术士", "AQ40Warlock" },
        { "战士", "AQ40Warrior" },
    },
    ["祖尔格拉布职业套装"] = {
        { "德鲁伊", "ZGDruid" },
        { "猎人", "ZGHunter" },
        { "法师", "ZGMage" },
        { "圣骑士", "ZGPaladin" },
        { "牧师", "ZGPriest" },
        { "盗贼", "ZGRogue" },
        { "萨满祭司", "ZGShaman" },
        { "术士", "ZGWarlock" },
        { "战士", "ZGWarrior" },
    },
    ["T0/T0.5 套装"] = {
        { "德鲁伊", "T0Druid" },
        { "猎人", "T0Hunter" },
        { "法师", "T0Mage" },
        { "圣骑士", "T0Paladin" },
        { "牧师", "T0Priest" },
        { "盗贼", "T0Rogue" },
        { "萨满祭司", "T0Shaman" },
        { "术士", "T0Warlock" },
        { "战士", "T0Warrior" },
    },
    ["T1 套装"] = {
        { "德鲁伊", "T1Druid" },
        { "猎人", "T1Hunter" },
        { "法师", "T1Mage" },
        { "圣骑士", "T1Paladin" },
        { "牧师", "T1Priest" },
        { "盗贼", "T1Rogue" },
        { "萨满祭司", "T1Shaman" },
        { "术士", "T1Warlock" },
        { "战士", "T1Warrior" },
    },
    ["T2 套装"] = {
        { "德鲁伊", "T2Druid" },
        { "猎人", "T2Hunter" },
        { "法师", "T2Mage" },
        { "圣骑士", "T2Paladin" },
        { "牧师", "T2Priest" },
        { "盗贼", "T2Rogue" },
        { "萨满祭司", "T2Shaman" },
        { "术士", "T2Warlock" },
        { "战士", "T2Warrior" },
    },
    ["T3 套装"] = {
        { "德鲁伊", "T3Druid" },
        { "猎人", "T3Hunter" },
        { "法师", "T3Mage" },
        { "圣骑士", "T3Paladin" },
        { "牧师", "T3Priest" },
        { "盗贼", "T3Rogue" },
        { "萨满祭司", "T3Shaman" },
        { "术士", "T3Warlock" },
        { "战士", "T3Warrior" },
    },
    ["银色黎明"] = {
        { "徽记换取", "Argent1" },
        { "友善/尊敬", "Argent2" },
        { "崇敬/崇拜", "Argent3" },
    },
    ["塞纳里奥议会"] = {
        { "友善", "Cenarion1" },
        { "尊敬", "Cenarion2" },
        { "崇敬", "Cenarion3" },
        { "崇拜", "Cenarion4" },
    },
    ["瑟银兄弟会"] = {
        { "友善", "Thorium1" },
        { "尊敬", "Thorium2" },
        { "崇敬", "Thorium3" },
        { "崇拜", "Thorium4" },
    },
    ["赞达拉部族"] = {
        { "友善", "Zandalar1" },
        { "尊敬", "Zandalar2" },
        { "崇敬", "Zandalar3" },
        { "崇拜", "Zandalar4" },
    },
    ["世界掉落"] = {
        { "武器", "WorldDrop1" },
        { "护甲", "WorldDrop2" },
    },
    ["奥特兰克山谷"] = {
        { "友善", "AVFriendly" },
        { "尊敬", "AVHonored" },
        { "崇敬", "AVRevered" },
        { "崇拜", "AVExalted" },
    },
    ["阿拉希盆地"] = {
        { "友善", "ABFriendly" },
        { "尊敬", "ABHonored" },
        { "崇敬", "ABRevered" },
        { "崇拜", "ABExalted" },
    },
    ["战歌峡谷"] = {
        { "友善", "WSGFriendly" },
        { "尊敬", "WSGHonored" },
        { "崇敬", "WSGRevered" },
        { "崇拜", "WSGExalted" },
    },
};

end        
    