
if GetLocale() == "zhCN" then
	DebuffTimersLocal = {
		-- Druid
		["精灵之火"] = "Faerie Fire",
		["精灵之火（野性）"] = "Faerie Fire (Feral)",
		["月火术"] = "Moonfire",
		["安抚动物"] = "Soothe Animal",
		["挑战咆哮"] = "Challenging Roar",
		["虫群"] = "Insect Swarm",
		["低吼"] = "Growl",
		["野性冲锋效果"] = "Feral Charge Effect",
		["血袭"] = "Pounce Bleed",
		["挫志咆哮"] = "Demoralizing Roar",
		["扫击"] = "Rake",
		["撕扯"] = "Rip",
		["纠缠根须"] = "Entangling Roots",
		["野性冲锋"] = "Feral Charge",
		["休眠"] = "Hibernate",
		["强化星火术"] = "Improved Starfire",
		["突袭"] = "Pounce",
		["重击"] = "Bash",
		["自然之握"] = "Nature's Grasp",
		
		-- Hunter
		["毒蝎钉刺"] = "Scorpid Sting",
		["毒蛇钉刺"] = "Serpent Sting",
		["蝰蛇钉刺"] = "Viper Sting",
		["震荡射击"] = "Concussive Shot",
		["翼龙钉刺"] = "Wyvern Sting",
		["摔绊"] = "Wing Clip",
		["爆炸陷阱效果"] = "Explosive Trap Effect",
		["献祭陷阱效果"] = "Immolation Trap Effect",
		["冰冻陷阱效果"] = "Freezing Trap Effect",
		["冰霜陷阱光环"] = "Frost Trap Aura",
		["强化震荡射击"] = "Improved Concussive Shot",
		["胁迫"] = "Intimidation",
		["恐吓野兽"] = "Scare Beast",
		["驱散射击"] = "Scatter Shot",
		["反击"] = "Counterattack",
		["强化摔绊"] = "Improved Wing Clip",	
		["诱捕"] = "Entrapment",
		["猎人印记"] = "Hunter's Mark",
		["爆炸陷阱"] = "Explosive Trap",
		["献祭陷阱"] = "Immolation Trap",
		["冰冻陷阱"] = "Freezing Trap",
		["冰霜陷阱"] = "Frost Trap",
		
		--Mage
		["侦测魔法"] = "Detect Magic",	
		["寒冰箭"] = "Frostbolt",	
		["冰锥术"] = "Cone of Cold",
		["法术反制 - 沉默"] = "Counterspell - Silenced",
		["火球术"] = "Fireball",
		["炎爆术"] = "Pyroblast",
		["点燃"] = "Ignite",
		["烈焰风暴"] = "Flamestrike",
		["冲击波"] = "Blast Wave",
		["冰冻"] = "Chilled",
		["变形术"] = "Polymorph",
		["变形术：奶牛"] = "Polymorph: Cow",
		["变形术：猪"] = "Polymorph: Pig",
		["变形术：龟"] = "Polymorph: Turtle",
		["冰霜新星"] = "Frost Nova",	
		["霜寒刺骨"] = "Frostbite",
		["元素易伤"] = "Elemental Vulnerability",
		["痛苦诅咒"] = "Fire Vulnerability",
		["深冬之寒"] = "Winter's Chill",
		["暴风雪"] = "Blizzard", --CFM 
		
		--Paladin
		["制裁之锤"] = "Hammer of Justice",
		["忏悔"] = "Repentance",
		["超度亡灵"] = "Turn Undead",
		
		--Priest
		["昏阙"] = "Blackout",
		["暗言术：痛 "] = "Shadow Word: Pain",
		["噬灵瘟疫"] = "Devouring Plague",
		["吸血鬼的拥抱"] = "Vampiric Embrace",
		["虚弱灵魂"] = "Weakened Soul",
		["神圣之火"] = "Holy Fire",
		["束缚亡灵"] = "Shackle Undead",
		["心灵尖啸"] = "Psychic Scream",
		["精神鞭笞"] = "Mind Flay",
		["精神控制"] = "Mind Control",

		--Rogue
		["破甲"] = "Expose Armor",
		["割裂"] = "Rupture",
		["绞喉"] = "Garrote",
		--["Ответный удар"] = "Riposte",
		["致残毒药"] = "Crippling Poison",
		["致命毒药"] = "Deadly Poison",
		["脚踢 - 沉默"] = "Kick - Silenced",
		["凿击"] = "Gouge",
		["致盲"] = "Blind",	
		["闷棍"] = "Sap",
		["肾击"] = "Kidney Shot",
		["偷袭"] = "Cheap Shot",

		--Shaman
		["冰霜震击"] = "Frost Shock",
		["烈焰震击"] = "Flame Shock",
		["冰封武器"] = "Frostbrand Weapon",
		["风暴打击"] = "Stormstrike",

		--Warlock
		["火焰冲撞"] = "Pyroclasm",
		["清算"] = "Aftermath",
		["暗影灼烧"] = "Shadowburn",
		["献祭"] = "Immolate",
		["腐蚀术"] = "Corruption",
		["痛苦诅咒"] = "Curse of Agony",
		["疲劳诅咒"] = "Curse of Exhaustion",
		["元素诅咒"] = "Curse of the Elements",
		["暗影诅咒"] = "Curse of Shadow",
		["语言诅咒"] = "Curse of Tongues",
		["虚弱诅咒"] = "Curse of Weakness",
		["鲁莽诅咒"] = "Curse of Recklessness",
		["厄运诅咒"] = "Curse of Doom",
		["生命虹吸"] = "Siphon Life",
		["暗影易伤"] = "Shadow Vulnerability",
		["法术封锁"] = "Spell Lock",
		["地狱火效果"] = "Inferno Effect",
		["残废术"] = "Cripple",
		["死亡缠绕"] = "Death Coil",
		["诱惑"] = "Seduction",
		["放逐术"] = "Banish",
		["恐惧术"] = "Fear",
		["恐惧嚎叫"] = "Howl of Terror",
		["吸取法力"] = "Drain Mana",
		["吸取生命"] = "Drain Life",
		["吸取灵魂"] = "Drain Soul",
		["腐坏之血效果"] = "Tainted Blood Effect",

		-- Warrior
		["缴械"] = "Disarm",
		["致死打击"] = "Mortal Strike",
		["雷霆一击"] = "Thunder Clap",
		["嘲讽"] = "Taunt",
		["惩戒痛击"] = "Mocking Blow",
		["挫志怒吼"] = "Demoralizing Shout",
		["挑战怒吼"] = "Challenging Shout",
		["破甲攻击"] = "Sunder Armor",
		["撕裂"] = "Rend",
		["断筋"] = "Hamstring",
		["强化断筋"] = "Improved Hamstring",
		["刺耳怒吼"] = "Piercing Howl",
		["冲锋击昏"] = "Charge Stun",
		["拦截昏迷"] = "Intercept Stun",
		["锤类武器专精"] = "Mace Specialization",
		["破胆怒吼"] = "Intimidating Shout",
		["复仇昏迷"] = "Revenge Stun",
		["震荡猛击"] = "Concussion Blow",

		--General
		["催眠术"] = "Sleep",
		["撒网器"] = "Net-o-Matic",
		["无畏冲锋"] = "Reckless Charge",
		["战争践踏"] = "War Stomp",
		
		--Parser
		["You fail to %a+ (.*):.*"] = "你未能 %a+ \"(.*)\":.*",
		["is immune to your (.*)%."] = "对你的(.*)%免疫。",
		["Your (.*) missed"] = "你的(.*)没有击中",
		["Your (.*) was resisted"] = "你的(.*)被(.+)抵抗",
		["Your (.*) was evaded"] = "你的(.*)被(.+)闪避",
		["Your (.*) was dodged"] = "你的(.*)被(.+)躲闪",
		["Your (.*) was deflected"] = "你的(.*)被(.+)偏斜",
		["Your (.*) is reflected"] = "你的(.*)被(.+)反弹",
		["Your (.*) is parried"] = "你的(.*)被(.+)招架",
		["(.+) fades from (.+)%."] = "(.+)效果从(.+)身上消失。",
		["(.+) suffers (.-)% (.-)% damage from your (.+)."]="你的(.+)使(.+)受到了(.-)%点(.-)%伤害", --CFM
		["(.+)'s (.+) is removed%."] = "(.+)的(.+)被移除了。",
		["(.+) is afflicted by (.+)%."] = "(.+)受到了(.+)效果的影响。",
		["(.-)%(Rank (%d+)%)"] = "(.-)%(等级 (%d+)%)",
		["(.+) dies"] = "(.+)死亡了。",
		["^([^%s']*)"] = "^([^%s'])",
		["Rank (%d+)"] = "等级 (%d+)",
	}
else
	DebuffTimersLocal = {
		-- Druid
		["Faerie Fire"] = "Faerie Fire",
		["Faerie Fire (Feral)"] = "Faerie Fire (Feral)",
		["Moonfire"] = "Moonfire",
		["Soothe Animal"] = "Soothe Animal",
		["Challenging Roar"] = "Challenging Roar",
		["Insect Swarm"] = "Insect Swarm",
		["Growl"] = "Growl",
		["Feral Charge Effect"] = "Feral Charge Effect",
		["Pounce Bleed"] = "Pounce Bleed",
		["Demoralizing Roar"] = "Demoralizing Roar",
		["Rake"] = "Rake",
		["Rip"] = "Rip",
		["Entangling Roots"] = "Entangling Roots",
		["Feral Charge"] = "Feral Charge",
		["Hibernate"] = "Hibernate",
		["Improved Starfire"] = "Improved Starfire",
		["Pounce"] = "Pounce",
		["Bash"] = "Bash",
		["Nature's Grasp"] = "Nature's Grasp",
		
		-- Hunter
		["Scorpid Sting"] = "Scorpid Sting",
		["Serpent Sting"] = "Serpent Sting",
		["Viper Sting"] = "Viper Sting",
		["Concussive Shot"] = "Concussive Shot",
		["Wyvern Sting"] = "Wyvern Sting",
		["Wing Clip"] = "Wing Clip",
		["Explosive Trap Effect"] = "Explosive Trap Effect",
		["Immolation Trap Effect"] = "Immolation Trap Effect",
		["Freezing Trap Effect"] = "Freezing Trap Effect",
		["Frost Trap Aura"] = "Frost Trap Aura",
		["Improved Concussive Shot"] = "Improved Concussive Shot",
		["Intimidation"] = "Intimidation",
		["Scare Beast"] = "Scare Beast",
		["Scatter Shot"] = "Scatter Shot",
		["Counterattack"] = "Counterattack",
		["Improved Wing Clip"] = "Improved Wing Clip",	
		["Entrapment"] = "Entrapment",
		["Hunter's Mark"] = "Hunter's Mark",
		["Explosive Trap"] = "Explosive Trap",
		["Immolation Trap"] = "Immolation Trap",
		["Freezing Trap"] = "Freezing Trap",
		["Frost Trap"] = "Frost Trap",
		
		--Mage
		["Detect Magic"] = "Detect Magic",	
		["Frostbolt"] = "Frostbolt",	
		["Cone of Cold"] = "Cone of Cold",
		["Counterspell - Silenced"] = "Counterspell - Silenced",
		["Fireball"] = "Fireball",
		["Pyroblast"] = "Pyroblast",
		["Ignite"] = "Ignite",
		["Flamestrike"] = "Flamestrike",
		["Blast Wave"] = "Blast Wave",
		["Chilled"] = "Chilled",
		["Polymorph"] = "Polymorph",
		["Polymorph: Cow"] = "Polymorph: Cow",
		["Polymorph: Pig"] = "Polymorph: Pig",
		["Polymorph: Turtle"] = "Polymorph: Turtle",
		["Frost Nova"] = "Frost Nova",	
		["Frostbite"] = "Frostbite",
		["Elemental Vulnerability"] = "Elemental Vulnerability",
		["Fire Vulnerability"] = "Fire Vulnerability",
		["Winter's Chill"] = "Winter's Chill",
		["Blizzard"] = "Blizzard", --CFM 

		--Paladin
		["Hammer of Justice"] = "Hammer of Justice",
		["Repentance"] = "Repentance",
		["Turn Undead"] = "Turn Undead",
		
		--Priest
		["Blackout"] = "Blackout",
		["Shadow Word: Pain"] = "Shadow Word: Pain",
		["Devouring Plague"] = "Devouring Plague",
		["Vampiric Embrace"] = "Vampiric Embrace",
		["Weakened Soul"] = "Weakened Soul",
		["Holy Fire"] = "Holy Fire",
		["Shackle Undead"] = "Shackle Undead",
		["Psychic Scream"] = "Psychic Scream",
		["Mind Flay"] = "Mind Flay",
		["Mind Control"] = "Mind Control",

		--Rogue
		["Expose Armor"] = "Expose Armor",
		["Rupture"] = "Rupture",
		["Garrote"] = "Garrote",
		["Riposte"] = "Riposte",
		["Crippling Poison"] = "Crippling Poison",
		["Deadly Poison"] = "Deadly Poison",
		["Kick - Silenced"] = "Kick - Silenced",
		["Gouge"] = "Gouge",
		["Blind"] = "Blind",	
		["Sap"] = "Sap",
		["Kidney Shot"] = "Kidney Shot",
		["Cheap Shot"] = "Cheap Shot",

		--Shaman
		["Frost Shock"] = "Frost Shock",
		["Flame Shock"] = "Flame Shock",
		["Frostbrand Weapon"] = "Frostbrand Weapon",
		["Stormstrike"] = "Stormstrike",

		--Warlock
		["Pyroclasm"] = "Pyroclasm",
		["Aftermath"] = "Aftermath",
		["Shadowburn"] = "Shadowburn",
		["Immolate"] = "Immolate",
		["Corruption"] = "Corruption",
		["Curse of Agony"] = "Curse of Agony",
		["Curse of Exhaustion"] = "Curse of Exhaustion",
		["Curse of the Elements"] = "Curse of the Elements",
		["Curse of Shadow"] = "Curse of Shadow",
		["Curse of Tongues"] = "Curse of Tongues",
		["Curse of Weakness"] = "Curse of Weakness",
		["Curse of Recklessness"] = "Curse of Recklessness",
		["Curse of Doom"] = "Curse of Doom",
		["Siphon Life"] = "Siphon Life",
		["Shadow Vulnerability"] = "Shadow Vulnerability",
		["Spell Lock"] = "Spell Lock",
		["Inferno Effect"] = "Inferno Effect",
		["Cripple"] = "Cripple",
		["Death Coil"] = "Death Coil",
		["Seduction"] = "Seduction",
		["Banish"] = "Banish",
		["Fear"] = "Fear",
		["Howl of Terror"] = "Howl of Terror",
		["Drain Mana"] = "Drain Mana",
		["Drain Life"] = "Drain Life",
		["Drain Soul"] = "Drain Soul",
		["Tainted Blood Effect"] = "Tainted Blood Effect",

		-- Warrior
		["Disarm"] = "Disarm",
		["Mortal Strike"] = "Mortal Strike",
		["Thunder Clap"] = "Thunder Clap",
		["Taunt"] = "Taunt",
		["Mocking Blow"] = "Mocking Blow",
		["Demoralizing Shout"] = "Demoralizing Shout",
		["Challenging Shout"] = "Challenging Shout",
		["Sunder Armor"] = "Sunder Armor",
		["Rend"] = "Rend",
		["Hamstring"] = "Hamstring",
		["Improved Hamstring"] = "Improved Hamstring",
		["Piercing Howl"] = "Piercing Howl",
		["Charge Stun"] = "Charge Stun",
		["Intercept Stun"] = "Intercept Stun",
		["Mace Specialization"] = "Mace Specialization",
		["Intimidating Shout"] = "Intimidating Shout",
		["Revenge Stun"] = "Revenge Stun",
		["Concussion Blow"] = "Concussion Blow",

		--General
		["Sleep"] = "Sleep",
		["Net-o-Matic"] = "Net-o-Matic",
		["Reckless Charge"] = "Reckless Charge",
		["War Stomp"] = "War Stomp",
		
		--Parser
		["You fail to %a+ (.*):.*"] = "You fail to %a+ (.*):.*",
		["is immune to your (.*)%."] = "is immune to your (.*)%.",
		["Your (.*) missed"] = "Your (.*) missed",
		["Your (.*) was resisted"] = "Your (.*) was resisted",
		["Your (.*) was evaded"] = "Your (.*) was evaded",
		["Your (.*) was dodged"] = "Your (.*) was dodged",
		["Your (.*) was deflected"] = "Your (.*) was deflected",
		["Your (.*) is reflected"] = "Your (.*) is reflected",
		["Your (.*) is parried"] = "Your (.*) is parried",
		["(.+) fades from (.+)%."] = "(.+) fades from (.+)%.",
		["(.+)'s (.+) is removed%."] = "(.+)'s (.+) is removed%.",
		["(.+) is afflicted by (.+)%."] = "(.+) is afflicted by (.+)%.",
		["(.+) suffers (.-)% (.-)% damage from your (.+)."]="(.+) suffers (.-)% (.-)% damage from your (.+).", --CFM
		["(.-)%(Rank (%d+)%)"] = "(.-)%(Rank (%d+)%)",
		["(.+) dies"] = "(.+) dies",
		["^([^%s']*)"] = "^([^%s']*)",
		["Rank (%d+)"] = "Rank (%d+)",
	}
end

