-- Version : Chinese ( by iWOW )
-- Last Update : 03/21/2005

if (GetLocale()=="zhTW") then

EARTHTREE_KEYWORD_TABLE="{表}";
EARTHTREE_KEYWORD_RECURSIVE_TABLE="{遞歸表}";
EARTHTREE_KEYWORD_BOOL_TRUE="|真|";
EARTHTREE_KEYWORD_BOOL_FALSE="|假|";
EARTHTREE_KEYWORD_FUNCTION="*函數*";
EARTHTREE_KEYWORD_NIL="空值";
EARTHTREE_KEYWORD_UNKNOWN="/未知類型/";

EARTHTREE_EXPAND_COLLAPSE="展開/收縮";
EARTHTREE_EXPAND_INFO="子節點: ";

EARTHTABLE_KEYWORD_TABLE="{表}";
EARTHTABLE_KEYWORD_FUNCTION="*函數*";
EARTHTABLE_KEYWORD_NIL="空值";
EARTHTABLE_KEYWORD_UNKNOWN="/未知/";
EARTHTABLE_KEYWORD_BOOL_TRUE="真";
EARTHTABLE_KEYWORD_BOOL_FALSE="假";

end