-- Version : Chinese ( by iWOW )
-- Last Update : 03/21/2005

if (GetLocale()=="zhCN") then

EARTHTREE_KEYWORD_TABLE="{表}";
EARTHTREE_KEYWORD_RECURSIVE_TABLE="{递归表}";
EARTHTREE_KEYWORD_BOOL_TRUE="|真|";
EARTHTREE_KEYWORD_BOOL_FALSE="|假|";
EARTHTREE_KEYWORD_FUNCTION="*函数*";
EARTHTREE_KEYWORD_NIL="空值";
EARTHTREE_KEYWORD_UNKNOWN="/未知类型/";

EARTHTREE_EXPAND_COLLAPSE="展开/收缩";
EARTHTREE_EXPAND_INFO="子节点: ";

EARTHTABLE_KEYWORD_TABLE="{表}";
EARTHTABLE_KEYWORD_FUNCTION="*函数*";
EARTHTABLE_KEYWORD_NIL="空值";
EARTHTABLE_KEYWORD_UNKNOWN="/未知/";
EARTHTABLE_KEYWORD_BOOL_TRUE="真";
EARTHTABLE_KEYWORD_BOOL_FALSE="假";

end
